// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe60igATR_0dQWJjDaLW7cEy5BrXRtZlA',
    appId: '1:95607013564:web:963dfeccd7a67c0fb9d0b9',
    messagingSenderId: '95607013564',
    projectId: 'myappsocialize',
    authDomain: 'myappsocialize.firebaseapp.com',
    storageBucket: 'myappsocialize.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR9ChJSMwMUbNOrs_HV69KmYpd9eJuZks',
    appId: '1:95607013564:android:8632c1d73bf888ccb9d0b9',
    messagingSenderId: '95607013564',
    projectId: 'myappsocialize',
    storageBucket: 'myappsocialize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3YrtbtuC08XK3AfL6LuIgUZMPTUCeYew',
    appId: '1:95607013564:ios:5502991043763309b9d0b9',
    messagingSenderId: '95607013564',
    projectId: 'myappsocialize',
    storageBucket: 'myappsocialize.appspot.com',
    androidClientId: '95607013564-3n1pfumiv2b97hfinvv0k9tidkqnpav6.apps.googleusercontent.com',
    iosClientId: '95607013564-mnu1vutmvbarrpgmf0ogp60c3uk0ncq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3YrtbtuC08XK3AfL6LuIgUZMPTUCeYew',
    appId: '1:95607013564:ios:1acb0289b8b7f515b9d0b9',
    messagingSenderId: '95607013564',
    projectId: 'myappsocialize',
    storageBucket: 'myappsocialize.appspot.com',
    androidClientId: '95607013564-3n1pfumiv2b97hfinvv0k9tidkqnpav6.apps.googleusercontent.com',
    iosClientId: '95607013564-n2dq2m28c8f8b3ih6fj06ejgfbe4ea0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat.RunnerTests',
  );
}
